// Week 5 - Class 1 - Employee Start
/* DELETE : import { Inter } from 'next/font/google'*/
/*const inter = Inter({ subsets: ['latin'] })*/

import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
